"""Port.is_authorized (baseline) e tabela cve_cache

Revision ID: 0abf5792c4ef
Revises: f1a2b3c4d5e6
Create Date: 2026-06-10 10:01:36.460563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abf5792c4ef'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product', 'version', name='uq_cve_product_version')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('alert_type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('NEW_DEVICE', 'NEW_IP_FOR_MAC', 'NEW_PORT', 'PORT_CLOSED', 'HOST_DOWN', 'SNMP_FAILURE', 'UNAUTHORIZED_DEVICE', 'IP_CONFLICT', 'ARP_SPOOFING', 'GHOST_DEVICE', 'TLS_CERT_EXPIRING', 'VULNERABILITY', name='alerttype'),
               existing_nullable=False)

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authorized', sa.Boolean(), nullable=False,
                                      server_default=sa.text('0')))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('snmp_community',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('snmp_community',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_column('is_authorized')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('alert_type',
               existing_type=sa.Enum('NEW_DEVICE', 'NEW_IP_FOR_MAC', 'NEW_PORT', 'PORT_CLOSED', 'HOST_DOWN', 'SNMP_FAILURE', 'UNAUTHORIZED_DEVICE', 'IP_CONFLICT', 'ARP_SPOOFING', 'GHOST_DEVICE', 'TLS_CERT_EXPIRING', 'VULNERABILITY', name='alerttype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    op.drop_table('cve_cache')
    # ### end Alembic commands ###
