"""SNMPv3, passive_only range, switch_neighbors topology

Revision ID: 0c70fb898bb8
Revises: 0abf5792c4ef
Create Date: 2026-07-13 14:49:06.812593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c70fb898bb8'
down_revision = '0abf5792c4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switch_neighbors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('switch_device_id', sa.Integer(), nullable=False),
    sa.Column('local_port', sa.String(length=120), nullable=False),
    sa.Column('remote_mac', sa.String(length=17), nullable=False),
    sa.Column('remote_name', sa.String(length=255), nullable=False),
    sa.Column('remote_port', sa.String(length=120), nullable=False),
    sa.Column('remote_device_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['remote_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['switch_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_device_id', 'local_port', 'remote_mac', name='uq_neighbor_switch_port_mac')
    )
    with op.batch_alter_table('switch_neighbors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_switch_neighbors_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_switch_neighbors_switch_device_id'), ['switch_device_id'], unique=False)

    # server_default garante que colunas NOT NULL sejam preenchidas nas linhas
    # já existentes (SQLite recusa NOT NULL sem default ao adicionar coluna).
    with op.batch_alter_table('ip_ranges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passive_only', sa.Boolean(), nullable=False,
                                      server_default=sa.text('0')))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snmp_v3_user', sa.Text(), nullable=False,
                                      server_default=''))
        batch_op.add_column(sa.Column('snmp_v3_auth_protocol', sa.String(length=10), nullable=False,
                                      server_default='SHA'))
        batch_op.add_column(sa.Column('snmp_v3_auth_key', sa.Text(), nullable=False,
                                      server_default=''))
        batch_op.add_column(sa.Column('snmp_v3_priv_protocol', sa.String(length=10), nullable=False,
                                      server_default='AES'))
        batch_op.add_column(sa.Column('snmp_v3_priv_key', sa.Text(), nullable=False,
                                      server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('snmp_v3_priv_key')
        batch_op.drop_column('snmp_v3_priv_protocol')
        batch_op.drop_column('snmp_v3_auth_key')
        batch_op.drop_column('snmp_v3_auth_protocol')
        batch_op.drop_column('snmp_v3_user')

    with op.batch_alter_table('ip_ranges', schema=None) as batch_op:
        batch_op.drop_column('passive_only')

    with op.batch_alter_table('switch_neighbors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_switch_neighbors_switch_device_id'))
        batch_op.drop_index(batch_op.f('ix_switch_neighbors_profile_id'))

    op.drop_table('switch_neighbors')
    # ### end Alembic commands ###
