"""add situation tags to device add note model

Revision ID: 273e8aa900ec
Revises: 4b9b3781130b
Create Date: 2026-03-31 09:21:58.706254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273e8aa900ec'
down_revision = '4b9b3781130b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situation', sa.String(length=100), nullable=False, server_default='NI'))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('situation')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_profile_id'))

    op.drop_table('notes')
    # ### end Alembic commands ###
