"""add device_online_snapshots table

Revision ID: 4b9b3781130b
Revises: 
Create Date: 2026-03-30 10:04:55.091085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9b3781130b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_online_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_online_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_online_snapshots_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_online_snapshots_recorded_at'), ['recorded_at'], unique=False)

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('device_online_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_online_snapshots_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_device_online_snapshots_profile_id'))

    op.drop_table('device_online_snapshots')
    # ### end Alembic commands ###
